""" update project table with link, code_link, image

Revision ID: 157886f4a430
Revises: 5d26191edb78
Create Date: 2022-04-15 13:15:11.788986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157886f4a430'
down_revision = '5d26191edb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.Column('link', sa.String(length=260), nullable=True),
    sa.Column('code_link', sa.String(length=260), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=260), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
