"""new init

Revision ID: 496cee4d3158
Revises: 20fc67dd2dea
Create Date: 2022-03-29 21:07:53.848196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496cee4d3158'
down_revision = '20fc67dd2dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('todo', 'picture_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('picture_url', sa.VARCHAR(length=260), nullable=True))
    op.drop_table('message')
    op.drop_table('user')
    # ### end Alembic commands ###
