"""added image to project model

Revision ID: 5bf1fdba6ee2
Revises: ccb159b2acad
Create Date: 2022-04-05 14:43:02.354181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf1fdba6ee2'
down_revision = 'ccb159b2acad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=260), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
