"""empty message

Revision ID: 600560446a59
Revises: c706d77f9ca8
Create Date: 2022-04-12 15:03:16.371848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600560446a59'
down_revision = 'c706d77f9ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=80), nullable=True),
    sa.Column('page', sa.VARCHAR(length=80), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
