"""added image to project model

Revision ID: 7abf9389bc00
Revises: 5813d1ba6bb6
Create Date: 2022-04-05 14:32:34.855761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abf9389bc00'
down_revision = '5813d1ba6bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_url', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_url')
    # ### end Alembic commands ###
