"""add picture_URL to Todo

Revision ID: 921320dc74a4
Revises: e257d84ec59c
Create Date: 2022-03-22 11:57:50.095943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921320dc74a4'
down_revision = 'e257d84ec59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('page', sa.String(length=80), nullable=True))
    op.add_column('todo', sa.Column('picture_url', sa.String(length=260), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'picture_url')
    op.drop_column('todo', 'page')
    # ### end Alembic commands ###
